AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
Documentation:
  Enabled: false
Rails:
  Enabled: true
Rails/FilePath:
  Exclude:
    - 'spec/**/*'
Metrics/LineLength:
  Max: 150
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/AbcSize:
  Max: 20
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Lint/ReturnInVoidContext:
  Enabled: false 
