inherit_from: .rubocop_todo.yml

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*" # specs can have long blocks
    - "*.gemspec"

